#!/usr/bin/python3
from commonlib import *

def main():
    """clean SQS"""
    sqs = boto3_resource('sqs')
    config = get_config()
    queue = sqs.Queue(config[CONFIG_SQS_URL])
    queue.delete()
    """clean S3 buckets"""
    s3 = boto3_resource('s3')
    bucket_input = s3.Bucket(NAME_BUCKET_INPUT)
    bucket_input.objects.all().delete()
    bucket_input.delete()
    bucket_output = s3.Bucket(NAME_BUCKET_OUTPUT)
    bucket_output.objects.all().delete()
    bucket_output.delete()
    
if __name__ == '__main__':
    main()
